# action.yml
name: 'Deploy to render'
description: 'Deploy the main branch to render if a push has been sent to main'
inputs:
  deploy_url:  # id of input
    description: 'The render deploy hook to access'
    required: true
  current_branch:
    description: 'The current branch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deploy_url }}
    - ${{ inputs.current_branch }}
