# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  deploy_url:  # id of input
    description: 'The render deploy hook to access'
    required: true
  current_branch:
    description: 'The current branch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deploy_url }}
    - ${{ inputs.current_branch }}
